name: elasticsearch
home: https://www.elastic.co/products/elasticsearch
version: 0.0.1
description: Elasticsearch chart for Kubernetes
sources:
  - https://www.elastic.co/products/elasticsearch
  - https://github.com/mrmm/elasticsearch-kubernetes
maintainers:
  - name: Mourad Maatoug
    email: mr.maatoug@gmail.com
