apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service_account" . }}
  #namespace: {{ template "namespace" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
    cluster-name: {{ template "cluster_name" . }}
    env: {{ .Values.Cluster.Env | quote }}
