apiVersion: v1
kind: Service
metadata:
  name: {{ template "discover_service" . }}
  #namespace: {{ template "namespace" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
    cluster-name: {{ template "cluster_name" . }}
    env: {{ .Values.Cluster.Env | quote }}
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    component: "{{.Release.Name}}-{{.Values.Component}}"
    cluster-name: {{ template "cluster_name" . }}
    env: {{ .Values.Cluster.Env | quote }}
    type: master
